### ISSUE TITLE
Add dummy creatures to encounter

### ISSUE THREAD

**Issue by meepcode** [maxiride/pf2e-encounters#33]
It would be useful to have the ability to add dummy creatures (with just a level and custom name) to the encounter panel, so that homebrew creatures can be used in this encounter builder, without having to add the ability to add custom creatures into the search area.

**Comment by maxiride** [comment]
Adding custom creatures permanently would involve complicating the website with more cookies/local storage use and while I'd accept a PR with such features I don't think I would implement it myself.

However, having a button to insert temporarily a creature with a custom name is doable, but I don't see any difference from e.g. adding a pre-existing creature in the DB with the desired level. You, the master building the encounter, know it's a dummy creature, and you are basically reskinning it.

Let me know your thoughts!
