### ISSUE TITLE
Creature Missing

### ISSUE THREAD

**Issue by AustinVockrodt** [maxiride/pf2e-encounters#39]
The Pukwudgie from Bestiary 3 pg. 208 is missing.

**Comment by maxiride** [comment]
If the creature is not present on the AON website itself I can't do anything about it. Have you checked if the creature is present in the official catalogue online?

**Comment by AustinVockrodt** [comment]
It is on the AoN. https://2e.aonprd.com/Monsters.aspx?ID=1269

**Comment by maxiride** [comment]
Thanks, I will check on it.

**Comment by bendking** [comment]
All the Pirate NPCs are missing as well:
http://2e.aonprd.com/NPCs.aspx?ID=952
